<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/15 0015
 * Time: 9:57
 */
namespace app\libs;
use yii;
class GetScore {
    /*判断对错（各科的对错，跨学科对错个数，subscore对错个数）

    大分数
    跨学科分数
    subscore
    */
    public function Number(){
        // 获取session 里的答案与数据库的答案对比得到个数 number['math'],number['reading']number['writing']number['math'],number['subscore'],

    }
    public function Score()
    {
        $number=$this->Number();
        if($number['math']==0||$number['math']==1){
            $score['math']=200;
        }elseif($number['math']==2){
            $score['math']=210;
        }elseif($number['math']==3){
            $score['math']=230;
        }elseif($number['math']==4){
            $score['math']=240;
        }elseif($number['math']==5){
            $score['math']=260;
        }elseif($number['math']==6){
            $score['math']=280;
        }elseif($number['math']==7){
            $score['math']=290;
        }elseif($number['math']==8){
            $score['math']=310;
        }elseif($number['math']==9){
            $score['math']=320;
        }elseif($number['math']==10){
            $score['math']=330;
        }elseif($number['math']==11){
            $score['math']=340;
        }elseif($number['math']==12){
            $score['math']=360;
        }elseif($number['math']==13){
            $score['math']=370;
        }elseif($number['math']==14){
            $score['math']=380;
        }elseif($number['math']==15){
            $score['math']=390;
        }elseif($number['math']==16){
            $score['math']=410;
        }elseif($number['math']==17){
            $score['math']=420;
        }elseif($number['math']==18){
            $score['math']=430;
        }elseif($number['math']==19){
            $score['math']=440;
        }elseif($number['math']==20){
            $score['math']=450;
        }elseif($number['math']==21){
            $score['math']=460;
        }elseif($number['math']==22){
            $score['math']=470;
        }elseif($number['math']==23||$number['math']==24){
            $score['math']=480;
        }elseif($number['math']==25){
            $score['math']=490;
        }elseif($number['math']==26){
            $score['math']=500;
        }elseif($number['math']==27){
            $score['math']=510;
        }elseif($number['math']==28||$number['math']==29){
            $score['math']=520;
        }elseif($number['math']==30){
            $score['math']=530;
        }elseif($number['math']==31){
            $score['math']=540;
        }elseif($number['math']==32){
            $score['math']=550;
        }elseif($number['math']==33||$number['math']==34){
            $score['math']=560;
        }elseif($number['math']==35){
            $score['math']=570;
        }elseif($number['math']==36){
            $score['math']=580;
        }elseif($number['math']==37){
            $score['math']=590;
        }elseif($number['math']==38||$number['math']==39){
            $score['math']=600;
        }elseif($number['math']==40){
            $score['math']=610;
        }elseif($number['math']==41){
            $score['math']=620;
        }elseif($number['math']==42){
            $score['math']=630;
        }elseif($number['math']==43){
            $score['math']=640;
        }elseif($number['math']==44){
            $score['math']=650;
        }elseif($number['math']==45){
            $score['math']=660;
        }elseif($number['math']==46||$number['math']==47){
            $score['math']=670;
        }elseif($number['math']==48){
            $score['math']=680;
        }elseif($number['math']==49){
            $score['math']=690;
        }elseif($number['math']==50){
            $score['math']=700;
        }elseif($number['math']==51){
            $score['math']=710;
        }elseif($number['math']==52){
            $score['math']=730;
        }elseif($number['math']==53){
            $score['math']=740;
        }elseif($number['math']==54){
            $score['math']=750;
        }elseif($number['math']==55){
            $score['math']=760;
        }elseif($number['math']==56){
            $score['math']=780;
        }elseif($number['math']==57){
            $score['math']=790;
        }else {
            $score['math'] = 800;
        }
        if($number['reading']==0||$number['reading']==1||$number['reading']==2){
            $score['reading']=10;
        }elseif($number['reading']==3){
            $score['reading']=11;
        }elseif($number['reading']==4){
            $score['reading']=12;
        }elseif($number['reading']==5){
            $score['reading']=13;
        }elseif($number['reading']==6){
            $score['reading']=14;
        }elseif($number['reading']==7||$number['reading']==8){
            $score['reading']=15;
        }elseif($number['reading']==9){
            $score['reading']=16;
        }elseif($number['reading']==10||$number['reading']==11){
            $score['reading']=17;
        }elseif($number['reading']==12){
            $score['reading']=18;
        }elseif($number['reading']==13||$number['reading']==14){
            $score['reading']=19;
        }elseif($number['reading']==15||$number['reading']==16){
            $score['reading']=20;
        }elseif($number['reading']==17||$number['reading']==18){
            $score['reading']=21;
        }elseif($number['reading']==19||$number['reading']==20){
            $score['reading']=22;
        }elseif($number['reading']==21||$number['reading']==22){
            $score['reading']=23;
        }elseif($number['reading']==23||$number['reading']==24){
            $score['reading']=24;
        }elseif($number['reading']==25||$number['reading']==26){
            $score['reading']=25;
        }elseif($number['reading']==27||$number['reading']==28){
            $score['reading']=26;
        }elseif($number['reading']==29){
            $score['reading']=27;
        }elseif($number['reading']==30||$number['reading']==31){
            $score['reading']=28;
        }elseif($number['reading']==32||$number['reading']==33){
            $score['reading']=29;
        }elseif($number['reading']==34||$number['reading']==35){
            $score['reading']=30;
        }elseif($number['reading']==36||$number['reading']==37){
            $score['reading']=31;
        }elseif($number['reading']==38||$number['reading']==39){
            $score['reading']=32;
        }elseif($number['reading']==40||$number['reading']==41){
            $score['reading']=33;
        }elseif($number['reading']==42){
            $score['reading']=34;
        }elseif($number['reading']==43||$number['reading']==44){
            $score['reading']=35;
        }elseif($number['reading']==45){
            $score['reading']=36;
        }elseif($number['reading']==46||$number['reading']==47){
            $score['reading']=37;
        }elseif($number['reading']==48||$number['reading']==49){
            $score['reading']=38;
        }elseif($number['reading']==50){
            $score['reading']=39;
        }else{
            $score['reading']=40;
        }
        if($number['writing']==0||$number['writing']==1||$number['writing']==2||$number['writing']==3){
            $score['writing']=10;
        }elseif($number['writing']==4){
            $score['writing']=11;
        }elseif($number['writing']==5){
            $score['writing']=12;
        }elseif($number['writing']==6||$number['writing']==7){
            $score['writing']=13;
        }elseif($number['writing']==8){
            $score['writing']=14;
        }elseif($number['writing']==9){
            $score['writing']=15;
        }elseif($number['writing']==10||$number['writing']==11){
            $score['writing']=16;
        }elseif($number['writing']==12){
            $score['writing']=17;
        }elseif($number['writing']==13){
            $score['writing']=18;
        }elseif($number['writing']==14||$number['writing']==15){
            $score['writing']=19;
        }elseif($number['writing']==16){
            $score['writing']=20;
        }elseif($number['writing']==17||$number['writing']==18){
            $score['writing']=21;
        }elseif($number['writing']==19){
            $score['writing']=22;
        }elseif($number['writing']==20||$number['writing']==21){
            $score['writing']=23;
        }elseif($number['writing']==22){
            $score['writing']=24;
        }elseif($number['writing']==23||$number['writing']==24){
            $score['writing']=25;
        }elseif($number['writing']==25||$number['writing']==26){
            $score['writing']=26;
        }elseif($number['writing']==27){
            $score['writing']=27;
        }elseif($number['writing']==28||$number['writing']==29){
            $score['writing']=28;
        }elseif($number['writing']==30){
            $score['writing']=29;
        }elseif($number['writing']==31||$number['writing']==32){
            $score['writing']=30;
        }elseif($number['writing']==33){
            $score['writing']=31;
        }elseif($number['writing']==34||$number['writing']==35){
            $score['writing']=32;
        }elseif($number['writing']==36){
            $score['writing']=33;
        }elseif($number['writing']==37||$number['writing']==38){
            $score['writing']=34;
        }elseif($number['writing']==39){
            $score['writing']=35;
        }elseif($number['writing']==40){
            $score['writing']=36;
        }elseif($number['writing']==41){
            $score['writing']=37;
        }elseif($number['writing']==42){
            $score['writing']=38;
        }elseif($number['writing']==43){
            $score['writing']=39;
        }elseif($number['writing']==44){
            $score['writing']=40;
        }
        return $score['math']+($score['writing']+$score['reading'])*10;
    }
    public function Subscore()
    {
        $number=$this->Number();
        if($number['expression']==0||$number['expression']==1||$number['expression']==2){
            $score['expression']=1;
        }elseif($number['expression']==3){
            $score['expression']=2;
        }elseif($number['expression']==4){
            $score['expression']=3;
        }elseif($number['expression']==5){
            $score['expression']=4;
        }elseif($number['expression']==6){
            $score['expression']=5;
        }elseif($number['expression']==7||$number['expression']==8){
            $score['expression']=6;
        }elseif($number['expression']==9||$number['expression']==10){
            $score['expression']=7;
        }elseif($number['expression']==11||$number['expression']==12){
            $score['expression']=8;
        }elseif($number['expression']==13||$number['expression']==14){
            $score['expression']=9;
        }elseif($number['expression']==15||$number['expression']==16){
            $score['expression']=10;
        }elseif($number['expression']==17||$number['expression']==18){
            $score['expression']=11;
        }elseif($number['expression']==19||$number['expression']==20){
            $score['expression']=12;
        }elseif($number['expression']==21){
            $score['expression']=13;
        }elseif($number['expression']==22||$number['expression']==23){
            $score['expression']=14;
        }else{
            $score['expression']=15;
        }
        if($number['english']==0||$number['english']==1||$number['english']==2){
            $score['english']=1;
        }elseif($number['english']==3||$number['english']==4){
            $score['english']=2;
        }elseif($number['english']==5){
            $score['english']=3;
        }elseif($number['english']==6){
            $score['english']=4;
        }elseif($number['english']==7){
            $score['english']=5;
        }elseif($number['english']==8||$number['english']==9){
            $score['english']=6;
        }elseif($number['english']==10||$number['english']==11){
            $score['english']=7;
        }elseif($number['english']==12||$number['english']==13){
            $score['english']=8;
        }elseif($number['english']==14){
            $score['english']=9;
        }elseif($number['english']==15||$number['english']==16){
            $score['english']=10;
        }elseif($number['english']==17){
            $score['english']=11;
        }elseif($number['english']==18){
            $score['english']=12;
        }elseif($number['english']==19){
            $score['english']=13;
        }else{
            $score['english']=15;
        }
        if($number['algebra']==0||$number['algebra']==1){
            $score['algebra']=1;
        }elseif($number['algebra']==2){
            $score['algebra']=2;
        }elseif($number['algebra']==3){
            $score['algebra']=3;
        }elseif($number['algebra']==4){
            $score['algebra']=4;
        }elseif($number['algebra']==5){
            $score['algebra']=5;
        }elseif($number['algebra']==6||$number['algebra']==7){
            $score['algebra']=6;
        }elseif($number['algebra']==8){
            $score['algebra']=7;
        }elseif($number['algebra']==9||$number['algebra']==10){
            $score['algebra']=8;
        }elseif($number['algebra']==11||$number['algebra']==12||$number['algebra']==13){
            $score['algebra']=9;
        }elseif($number['algebra']==14||$number['algebra']==15){
            $score['algebra']=10;
        }elseif($number['algebra']==16){
            $score['algebra']=11;
        }elseif($number['algebra']==17){
            $score['algebra']=12;
        }elseif($number['algebra']==18){
            $score['algebra']=13;
        }else{
            $score['algebra']=15;
        }
        if($number['analysis']==0||$number['analysis']==1){
            $score['analysis']=1;
        }elseif($number['analysis']==2){
            $score['analysis']=2;
        }elseif($number['analysis']==3){
            $score['analysis']=3;
        }elseif($number['analysis']==4){
            $score['analysis']=4;
        }elseif($number['analysis']==5){
            $score['analysis']=5;
        }elseif($number['analysis']==6){
            $score['analysis']=6;
        }elseif($number['analysis']==7){
            $score['analysis']=7;
        }elseif($number['analysis']==8||$number['analysis']==9){
            $score['analysis']=8;
        }elseif($number['analysis']==10){
            $score['analysis']=9;
        }elseif($number['analysis']==11||$number['analysis']==12){
            $score['analysis']=10;
        }elseif($number['analysis']==13){
            $score['analysis']=11;
        }elseif($number['analysis']==14){
            $score['analysis']=12;
        }elseif($number['analysis']==15){
            $score['analysis']=13;
        }elseif($number['analysis']==16){
            $score['analysis']=14;
        }else{
            $score['analysis']=15;
        }
        if($number['math']==0||$number['math']==1){
            $score['math']=1;
        }elseif($number['math']==2){
            $score['math']=2;
        }elseif($number['math']==3){
            $score['math']=3;
        }elseif($number['math']==4){
            $score['math']=4;
        }elseif($number['math']==5){
            $score['math']=5;
        }elseif($number['math']==6){
            $score['math']=6;
        }elseif($number['math']==7){
            $score['math']=7;
        }elseif($number['math']==8){
            $score['math']=8;
        }elseif($number['math']==9){
            $score['math']=9;
        }elseif($number['math']==10||$number['math']==11){
            $score['math']=10;
        }elseif($number['math']==12){
            $score['math']=11;
        }elseif($number['math']==13){
            $score['math']=12;
        }elseif($number['math']==14){
            $score['math']=13;
        }elseif($number['math']==15){
            $score['math']=14;
        }elseif($number['math']==16){
            $score['math']=15;
        }
        if($number['words']==0||$number['words']==1){
            $score['words']=1;
        }elseif($number['words']==2){
            $score['words']=2;
        }elseif($number['words']==3){
            $score['words']=3;
        }elseif($number['words']==4){
            $score['words']=4;
        }elseif($number['words']==5){
            $score['words']=5;
        }elseif($number['words']==6||$number['words']==7){
            $score['words']=6;
        }elseif($number['words']==8){
            $score['words']=7;
        }elseif($number['words']==9||$number['words']==10){
            $score['words']=8;
        }elseif($number['words']==11||$number['words']==12){
            $score['words']=9;
        }elseif($number['words']==13){
            $score['words']=10;
        }elseif($number['words']==14){
            $score['words']=11;
        }elseif($number['words']==15){
            $score['words']=12;
        }elseif($number['words']==16){
            $score['words']=13;
        }elseif($number['words']==17){
            $score['words']=14;
        }elseif($number['words']==18){
            $score['words']=15;
        }
        if($number['evidence']==0||$number['evidence']==1){
            $score['evidence']=1;
        }elseif($number['evidence']==2){
            $score['evidence']=2;
        }elseif($number['evidence']==3){
            $score['evidence']=3;
        }elseif($number['evidence']==4){
            $score['evidence']=4;
        }elseif($number['evidence']==5){
            $score['evidence']=5;
        }elseif($number['evidence']==6){
            $score['evidence']=6;
        }elseif($number['evidence']==7){
            $score['evidence']=7;
        }elseif($number['evidence']==8||$number['evidence']==9){
            $score['evidence']=8;
        }elseif($number['evidence']==10){
            $score['evidence']=9;
        }elseif($number['evidence']==11||$number['evidence']==12){
            $score['evidence']=10;
        }elseif($number['evidence']==13){
            $score['evidence']=11;
        }elseif($number['evidence']==14){
            $score['evidence']=12;
        }elseif($number['evidence']==15){
            $score['evidence']=13;
        }elseif($number['evidence']==16){
            $score['evidence']=14;
        }elseif($number['evidence']==17||$number['evidence']==18){
            $score['evidence']=15;
        }
        $subcsores=$score['expression']+$score['english']+$score['algebra']+ $score['analysis']+$score['analysis']+ $score['math']+$score['words']+$score['evidence'];
        return $subcsores;
    }
    public function CrossTest()
    {
        $number=$this->Number();
        if($number['social']==0||$number['social']==1){
            $score['social']=10;
        }elseif($number['social']==2){
            $score['social']=11;
        }elseif($number['social']==3){
            $score['social']=12;
        }elseif($number['social']==4){
            $score['social']=14;
        }elseif($number['social']==5){
            $score['social']=15;
        }elseif($number['social']==6){
            $score['social']=16;
        }elseif($number['social']==7){
            $score['social']=17;
        }elseif($number['social']==8){
            $score['social']=18;
        }elseif($number['social']==9){
            $score['social']=20;
        }elseif($number['social']==10){
            $score['social']=21;
        }elseif($number['social']==11){
            $score['social']=22;
        }elseif($number['social']==12){
            $score['social']=23;
        }elseif($number['social']==13){
            $score['social']=24;
        }elseif($number['social']==14){
            $score['social']=25;
        }elseif($number['social']==15){
            $score['social']=26;
        }elseif($number['social']==16){
            $score['social']=27;
        }elseif($number['social']==17||$number['social']==18){
            $score['social']=28;
        }elseif($number['social']==19){
            $score['social']=29;
        }elseif($number['social']==20||$number['social']==21){
            $score['social']=30;
        }elseif($number['social']==22){
            $score['social']=31;
        }elseif($number['social']==23||$number['social']==24){
            $score['social']=32;
        }elseif($number['social']==25){
            $score['social']=33;
        }elseif($number['social']==26){
            $score['social']=34;
        }elseif($number['social']==27||$number['social']==28){
            $score['social']=35;
        }elseif($number['social']==29){
            $score['social']=36;
        }elseif($number['social']==30){
            $score['social']=37;
        }elseif($number['social']==31||$number['social']==32){
            $score['social']=38;
        }elseif($number['social']==33){
            $score['social']=39;
        }elseif($number['social']==34||$number['social']==35){
            $score['social']=40;
        }
        if($number['science']==0){
            $score['science']=10;
        }elseif($number['science']==1){
            $score['science']=11;
        }elseif($number['science']==2){
            $score['science']=12;
        }elseif($number['science']==3){
            $score['science']=13;
        }elseif($number['science']==4){
            $score['science']=14;
        }elseif($number['science']==5){
            $score['science']=15;
        }elseif($number['science']==6){
            $score['science']=16;
        }elseif($number['science']==7){
            $score['science']=17;
        }elseif($number['science']==8){
            $score['science']=18;
        }elseif($number['science']==9){
            $score['science']=19;
        }elseif($number['science']==10||$number['science']==11){
            $score['science']=20;
        }elseif($number['science']==12){
            $score['science']=21;
        }elseif($number['science']==13){
            $score['science']=22;
        }elseif($number['science']==14){
            $score['science']=23;
        }elseif($number['science']==15||$number['science']==16){
            $score['science']=24;
        }elseif($number['science']==17){
            $score['science']=25;
        }elseif($number['science']==18){
            $score['science']=26;
        }elseif($number['science']==19||$number['science']==20){
            $score['science']=27;
        }elseif($number['science']==21){
            $score['science']=28;
        }elseif($number['science']==22){
            $score['science']=29;
        }elseif($number['science']==23||$number['science']==24){
            $score['science']=30;
        }elseif($number['science']==25){
            $score['science']=31;
        }elseif($number['science']==26){
            $score['science']=32;
        }elseif($number['science']==27||$number['science']==28){
            $score['science']=33;
        }elseif($number['science']==29){
            $score['science']=34;
        }elseif($number['science']==30){
            $score['science']=35;
        }elseif($number['science']==31){
            $score['science']=36;
        }elseif($number['science']==32){
            $score['science']=37;
        }elseif($number['science']==33){
            $score['science']=38;
        }elseif($number['science']==34){
            $score['science']=39;
        }elseif($number['science']==35){
            $score['science']=40;
        }
        return $score;
    }
}